
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_I2CS_DEVICE_ID,
		XPAR_I2CS_BASEADDR,
		XPAR_I2CS_INTERRUPT_PRESENT,
		XPAR_I2CS_IS_DUAL
	},
	{
		XPAR_PWDN_DEVICE_ID,
		XPAR_PWDN_BASEADDR,
		XPAR_PWDN_INTERRUPT_PRESENT,
		XPAR_PWDN_IS_DUAL
	},
	{
		XPAR_VIDEO_IN_ACTIVE_DEVICE_ID,
		XPAR_VIDEO_IN_ACTIVE_BASEADDR,
		XPAR_VIDEO_IN_ACTIVE_INTERRUPT_PRESENT,
		XPAR_VIDEO_IN_ACTIVE_IS_DUAL
	},
	{
		XPAR_VSYNC_DEVICE_ID,
		XPAR_VSYNC_BASEADDR,
		XPAR_VSYNC_INTERRUPT_PRESENT,
		XPAR_VSYNC_IS_DUAL
	}
};


