######################################################################
#
# File name : tb_camera_dvp_simulator_compile.do
# Created on: Mon Oct 23 20:33:00 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../sc_camera_dvp.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../sc_camera_dvp.gen/sources_1/bd/system/ipshared/3007/hdl" "+incdir+D:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
"../../../../sc_camera_dvp.srcs/sources_1/new/camera_dvp_simulator.v" \
"../../../../sc_camera_dvp.srcs/sim_1/new/tb_camera_dvp_simulator.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

