######################################################################
#
# File name : tb_camera_dvp_simulator_simulate.do
# Created on: Mon Oct 23 20:33:03 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_camera_dvp_simulator xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_camera_dvp_simulator_wave.do}

view wave
view structure
view signals

do {tb_camera_dvp_simulator.udo}

run 1000ns
