######################################################################
#
# File name : tb_camera_dvp_simulator_wave.do
# Created on: Mon Oct 23 20:33:03 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
