#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Thu Feb 22 23:04:43 +0800 2024
# SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : bd_system.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : bd_system.sh
#                bd_system.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                bd_system.sh [-reset_run]
#                bd_system.sh [-reset_log]
#                bd_system.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'bd_system.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm xil_defaultlib xlconstant_v1_1_8 lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_29 axi_vip_v1_1_15 lib_pkg_v1_0_3 fifo_generator_v13_2_9 lib_fifo_v1_0_18 blk_mem_gen_v8_4_7 lib_bmg_v1_0_16 lib_srl_fifo_v1_0_3 axi_datamover_v5_1_31 axi_vdma_v6_3_17 processing_system7_vip_v1_0_17 generic_baseblocks_v2_1_1 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_17 v_tc_v6_2_7 v_vid_in_axi4s_v5_0_3 interrupt_control_v3_1_5 axi_gpio_v2_0_31 axi_protocol_converter_v2_1_29)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "bd_system.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./bd_system.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ipshared/31a1/src/asyn_rst_syn.v" \
  "../../../bd/bd_system/ipshared/31a1/src/dvi_encoder.v" \
  "../../../bd/bd_system/ipshared/31a1/src/serializer_10_to_1.v" \
  "../../../bd/bd_system/ipshared/31a1/src/dvi_transmitter_top.v" \
  "../../../bd/bd_system/ip/bd_system_DVI_Transmitter_0_0/sim/bd_system_DVI_Transmitter_0_0.v" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ab26/src/mmcme2_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ab26/src/axi_dynclk_S00_AXI.vhd" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ab26/src/axi_dynclk.vhd" \
  "../../../bd/bd_system/ip/bd_system_axi_dynclk_0_0/sim/bd_system_axi_dynclk_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/sim/bd_3952.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_8 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_0/sim/bd_3952_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_14 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_1/sim/bd_3952_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_2/sim/bd_3952_arsw_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_3/sim/bd_3952_rsw_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_4/sim/bd_3952_awsw_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_5/sim/bd_3952_wsw_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_6/sim/bd_3952_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_7/sim/bd_3952_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_8/sim/bd_3952_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_9/sim/bd_3952_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_10/sim/bd_3952_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_11/sim/bd_3952_sarn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_12/sim/bd_3952_srn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_13/sim/bd_3952_s01mmu_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_14/sim/bd_3952_s01tr_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_15/sim/bd_3952_s01sic_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_16/sim/bd_3952_s01a2s_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_17/sim/bd_3952_sawn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_18/sim/bd_3952_swn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_19/sim/bd_3952_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_20/sim/bd_3952_m00s2a_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_21/sim/bd_3952_m00arn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_22/sim/bd_3952_m00rn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_23/sim/bd_3952_m00awn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_24/sim/bd_3952_m00wn_0.sv" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_25/sim/bd_3952_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/bd_0/ip/ip_26/sim/bd_3952_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_29 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_15 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_axi_smc_0/sim/bd_system_axi_smc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_pkg_v1_0_3 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_9 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work fifo_generator_v13_2_9 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_9 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_fifo_v1_0_18 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_7 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work lib_bmg_v1_0_16 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/5c9c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_srl_fifo_v1_0_3 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_datamover_v5_1_31 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_vdma_v6_3_17 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_vdma_v6_3_17 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_axi_vdma_0_0/sim/bd_system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work processing_system7_vip_v1_0_17 $vlogan_opts -sverilog +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_processing_system7_0_0/sim/bd_system_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work generic_baseblocks_v2_1_1 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_data_fifo_v2_1_28 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_crossbar_v2_1_30 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_xbar_0/sim/bd_system_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_rst_ps7_0_100M_0/sim/bd_system_rst_ps7_0_100M_0.vhd" \
  "../../../bd/bd_system/ip/bd_system_rst_ps7_0_50M_0/sim/bd_system_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work v_vid_in_axi4s_v4_0_11 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work v_axi4s_vid_out_v4_0_17 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/b7a6/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_v_axi4s_vid_out_0_0/sim/bd_system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work v_tc_v6_2_7 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/0e63/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_v_tc_0_0/sim/bd_system_v_tc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work v_vid_in_axi4s_v5_0_3 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7302/hdl/v_vid_in_axi4s_v5_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_v_vid_in_axi4s_0_0/sim/bd_system_v_vid_in_axi4s_0_0.v" \
  "../../../bd/bd_system/ip/bd_system_sc035hgs_0_0/sim/bd_system_sc035hgs_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work interrupt_control_v3_1_5 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_gpio_v2_0_31 $vhdlan_opts \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_axi_gpio_0_0/sim/bd_system_axi_gpio_0_0.vhd" \
  "../../../bd/bd_system/ip/bd_system_axi_gpio_0_1/sim/bd_system_axi_gpio_0_1.vhd" \
  "../../../bd/bd_system/ip/bd_system_axi_gpio_0_2/sim/bd_system_axi_gpio_0_2.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/sim/bd_system.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/bd_system/ip/bd_system_axi_gpio_0_3/sim/bd_system_axi_gpio_0_3.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work axi_protocol_converter_v2_1_29 $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/35de/hdl/verilog" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/ec67/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/7fb4/hdl" +incdir+"../../../../sc035hgs_hdmi.gen/sources_1/bd/bd_system/ipshared/6b2b/hdl" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/bd_system/ip/bd_system_auto_pc_0/sim/bd_system_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.bd_system xil_defaultlib.glbl -o bd_system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./bd_system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key bd_system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc bd_system_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./bd_system.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: bd_system.sh [-help]\n\
Usage: bd_system.sh [-step]\n\
Usage: bd_system.sh [-lib_map_path]\n\
Usage: bd_system.sh [-reset_run]\n\
Usage: bd_system.sh [-reset_log]\n\
Usage: bd_system.sh [-keep_index]\n\
Usage: bd_system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
