
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXIS_TRANSMIT_ENABLE_DEVICE_ID,
		XPAR_AXIS_TRANSMIT_ENABLE_BASEADDR,
		XPAR_AXIS_TRANSMIT_ENABLE_INTERRUPT_PRESENT,
		XPAR_AXIS_TRANSMIT_ENABLE_IS_DUAL
	},
	{
		XPAR_CAMERA_PWDN_DEVICE_ID,
		XPAR_CAMERA_PWDN_BASEADDR,
		XPAR_CAMERA_PWDN_INTERRUPT_PRESENT,
		XPAR_CAMERA_PWDN_IS_DUAL
	},
	{
		XPAR_CAMERA_RESET_DEVICE_ID,
		XPAR_CAMERA_RESET_BASEADDR,
		XPAR_CAMERA_RESET_INTERRUPT_PRESENT,
		XPAR_CAMERA_RESET_IS_DUAL
	},
	{
		XPAR_CAMERA_VSYNC_DEVICE_ID,
		XPAR_CAMERA_VSYNC_BASEADDR,
		XPAR_CAMERA_VSYNC_INTERRUPT_PRESENT,
		XPAR_CAMERA_VSYNC_IS_DUAL
	},
	{
		XPAR_PHY_RESET_DEVICE_ID,
		XPAR_PHY_RESET_BASEADDR,
		XPAR_PHY_RESET_INTERRUPT_PRESENT,
		XPAR_PHY_RESET_IS_DUAL
	}
};


