# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xci
# IP: The module: 'ov5640_hdmi_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xci
# IP: The module: 'ov5640_hdmi_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
