# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/58e2/hdl
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/979d/hdl/verilog
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/b2d0/hdl/verilog
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl
  } {
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/58e2/hdl
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/979d/hdl/verilog
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/b2d0/hdl/verilog
    g:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl
  } {
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_processing_system7_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_axi_vdma_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_v_vid_in_axi4s_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_ov5640_capture_data_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_v_axi4s_vid_out_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_DVI_Transmitter_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_axi_dynclk_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_v_tc_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_axi_smc_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_rst_ps7_0_100M_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_xbar_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_auto_pc_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_divider2_0_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/realtime/ov5640_hdmi_divider2_1_0_stub.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/synth/ov5640_hdmi.v
      G:/FPGA_pjt/ov5640_hdmi_1_2/ov5640_hdmi.srcs/sources_1/bd/ov5640_hdmi/hdl/ov5640_hdmi_wrapper.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ov5640_hdmi_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "G:/FPGA_pjt/ov5640_hdmi_1_2/.Xil/Vivado-15460-DESKTOP-3CJBT8S/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
