# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
# IP: The module: 'system_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
# IP: The module: 'system_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/sc_camera/code/dma_pl2ps/dma_pl2ps.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
