set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_pclk]


set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_pixel_data[0]}]
set_property PACKAGE_PIN T16 [get_ports {i_pixel_data[7]}]
set_property PACKAGE_PIN R17 [get_ports {i_pixel_data[6]}]
set_property PACKAGE_PIN W16 [get_ports {i_pixel_data[5]}]
set_property PACKAGE_PIN W20 [get_ports {i_pixel_data[4]}]
set_property PACKAGE_PIN R18 [get_ports {i_pixel_data[3]}]
set_property PACKAGE_PIN V20 [get_ports {i_pixel_data[2]}]
set_property PACKAGE_PIN P19 [get_ports {i_pixel_data[1]}]
set_property PACKAGE_PIN U20 [get_ports {i_pixel_data[0]}]
set_property PACKAGE_PIN T17 [get_ports i_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports i_pclk]
set_property PACKAGE_PIN N18 [get_ports i_href]
set_property IOSTANDARD LVCMOS33 [get_ports i_href]
set_property PACKAGE_PIN N20 [get_ports i_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports i_vsync]
set_property PACKAGE_PIN W18 [get_ports o_xclk_24MHz]
set_property IOSTANDARD LVCMOS33 [get_ports o_xclk_24MHz]
set_property PACKAGE_PIN F17 [get_ports o_tmds_oen]
set_property IOSTANDARD LVCMOS33 [get_ports o_tmds_oen]
set_property PACKAGE_PIN C20 [get_ports {o_tmds_tmds_data_p[1]}]
set_property PACKAGE_PIN D19 [get_ports {o_tmds_tmds_data_p[0]}]
set_property PACKAGE_PIN H16 [get_ports o_tmds_tmds_clk_p]
set_property PACKAGE_PIN B19 [get_ports {o_tmds_tmds_data_p[2]}]
set_property PACKAGE_PIN P20 [get_ports {gpio_tri_io[0]}]
set_property PULLUP true [get_ports {gpio_tri_io[0]}]
set_property PACKAGE_PIN T20 [get_ports {gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[0]}]
set_property PULLUP true [get_ports {gpio_tri_io[1]}]
set_property PACKAGE_PIN P18 [get_ports {gpio_tri_io[2]}]



set_property PACKAGE_PIN U18 [get_ports {gpio_tri_io[3]}]
set_property PACKAGE_PIN T12 [get_ports {gpio_tri_io[4]}]


