# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TOP.xdc

# Block Designs: bd/ov5640_hdmi/ov5640_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi || ORIG_REF_NAME==ov5640_hdmi} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_DVI_Transmitter_0_0/ov5640_hdmi_DVI_Transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_DVI_Transmitter_0_0 || ORIG_REF_NAME==ov5640_hdmi_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_axi_dynclk_0_0/ov5640_hdmi_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_axi_dynclk_0_0 || ORIG_REF_NAME==ov5640_hdmi_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_axi_smc_1/ov5640_hdmi_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_axi_smc_1 || ORIG_REF_NAME==ov5640_hdmi_axi_smc_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==ov5640_hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_ov5640_capture_data_0_0/ov5640_hdmi_ov5640_capture_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_ov5640_capture_data_0_0 || ORIG_REF_NAME==ov5640_hdmi_ov5640_capture_data_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_processing_system7_0_0/ov5640_hdmi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_processing_system7_0_0 || ORIG_REF_NAME==ov5640_hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_xbar_0/ov5640_hdmi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_xbar_0 || ORIG_REF_NAME==ov5640_hdmi_xbar_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_auto_pc_0/ov5640_hdmi_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_auto_pc_0 || ORIG_REF_NAME==ov5640_hdmi_auto_pc_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_ps7_0_axi_periph_1/ov5640_hdmi_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_ps7_0_axi_periph_1 || ORIG_REF_NAME==ov5640_hdmi_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_100M_1/ov5640_hdmi_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_rst_ps7_0_100M_1 || ORIG_REF_NAME==ov5640_hdmi_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_50M_0/ov5640_hdmi_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_rst_ps7_0_50M_0 || ORIG_REF_NAME==ov5640_hdmi_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_axi4s_vid_out_0_0/ov5640_hdmi_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_tc_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_tc_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_vid_in_axi4s_0_0/ov5640_hdmi_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_vid_in_axi4s_0_0} -quiet] -quiet

# XDC: e:/Project/sc_camera/code/20220731ygACd6Xc/ov5640_hdmi_1_3/ov5640_hdmi.gen/sources_1/bd/ov5640_hdmi/ov5640_hdmi_ooc.xdc
